version: "3.3"

services:
    
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - ~/volumes/socnetdb/mongo/data:/data/db
      - ~/volumes/socnetdb/mongo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DonDev
      - MONGO_INITDB_ROOT_PASSWORD=BC2022     
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
 
     
  student:
    image: student     
    build: ./student
    container_name: student   
    links:
      - mongodb
    ports:
      - 9095:9095 
    depends_on:
      - mongodb
    deploy:
      replicas: 1
    networks:
     - mnet
  
  courses:
    image: courses     
    build: ./courses
    container_name: courses   
    links:
      - mongodb
    ports:
      - 9096:9096 
    depends_on:
      - mongodb
    deploy:
      replicas: 1
    networks:
      - mnet
      
  gateway:
    image: gateway     
    build: ./gateway
    container_name: gateway   
    links:
      - mongodb
    ports:
      - 9097:9097
    depends_on:
      - mongodb
    deploy:
      replicas: 1
    networks:
      - mnet
     
networks:
  mnet:
    driver: bridge
